dist: xenial
language: go
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'
go:
  - master
notifications:
  email: false
before_install:
  - go get -u golang.org/x/lint/golint
script:
  - go test -v -race ./...
  - golint ./...
